# vim: set ft=ansible:
---
- name: Configure the nodes
  hosts: ec2
  gather_facts: no
#  connection: local
  become: True
  become_method: sudo
  vars_files:
    - vars.yaml
  tasks:

  - name: Debug ec2 host group
    debug: var=groups.ec2

  - name: Copy partition script
    copy:
      src: ./partition.sh
      dest: /tmp/partition.sh
      owner: root
      mode: 0700

  - name: Execute the partition script
    shell: /tmp/partition.sh

  - name: Format EBS volume
    filesystem:
      fstype: xfs
      dev: /dev/xvdb1

  - name: Make the bricks directory
    file:
      path: "/bricks/brick1"
      state: directory
      mode: 0755
      recurse: yes

  - name: Mount the volume
    mount:
      name: "/bricks/brick1"
      src: /dev/xvdb1
      fstype: xfs
      state: mounted

  - name: Create the brick sub-directory
    file:
      path: "/bricks/brick1/brick"
      state: directory
      mode: 0755
      recurse: yes