# vim: set ft=ansible:
---
- name: Configure the VPC
  hosts: localhost
  gather_facts: no
  connection: local
  become: False
  vars_files:
    - vars.yaml

  tasks:

  - name: Create ec2 vpc
    ec2_vpc:
      state: present
      dns_support: yes
      dns_hostnames: yes
      cidr_block: 172.18.0.0/16
      resource_tags:
        env: "{{ cluster_id }}"
        Name: "{{ cluster_id }}-vpc"
      region: "{{ ec2_region }}"
      subnets:
      - cidr: 172.18.1.0/24
        az: "{{ ec2_region }}a"
        resource_tags:
          env: "{{ cluster_id }}"
          Name: "{{ cluster_id }}-subnet-a"
      - cidr: 172.18.2.0/24
        az: "{{ ec2_region }}c"
        resource_tags:
          env: "{{ cluster_id }}"
          Name: "{{ cluster_id }}-subnet-b"
      internet_gateway: yes
      route_tables:
      - subnets:
        - 172.18.1.0/24
        - 172.18.2.0/24
        routes:
        - dest: 0.0.0.0/0
          gw: igw
        resource_tags:
          Name: "{{ cluster_id }}-route"
          env: "{{ cluster_id }}"
      wait: yes
    register: vpc

  - name: Debug vpc data structure
    debug: var=vpc
    when: debug_print == true