# vim: set ft=ansible:
---
- name: Configure the VPC
  hosts: localhost
  gather_facts: no
  connection: local
  become: False
  vars_files:
    - vars.yaml

  tasks:
  - name: create the Route 53 hosted zone
    route53_zone:
      zone: "{{ r53_zone }}"
      state: present
