# vim: set ft=ansible:
---
- name: Configure the security groups
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars_files:
    - vars.yaml
  tasks:
  - name: Create ec2 node security group
    ec2_group:
      region: "{{ ec2_region }}"
      vpc_id: "{{ vpc_id }}"
      name: "{{ cluster_id }}-node"
      description: "{{ cluster_id }} nodes"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: all
        group_name: "{{ cluster_id }}-node"
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: group