# vim: set ft=ansible:
---
- name: Configure the nodes on side a
  hosts: localhost
  gather_facts: no
  connection: local
  become: no
  vars_files:
    - vars.yaml
  tasks:

  - name: Create ec2 instance
    ec2:
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      key_name: "{{ ec2_keypair }}"
      instance_type: "{{ ec2_instance_type }}"
      group: "{{ cluster_id }}-node }}"
      exact_count: "{{ nodes_per_az }}"
      wait: yes
      instance_tags:
        Name: "{{ cluster_id }}"
      volumes:
        - volume_size: 10
          device_type: gp2
          device_name: /dev/sda1
          delete_on_termination: True
        - device_name: /dev/xvdb
          device_type: gp2
          volume_size: 10
          delete_on_termination: True
      vpc_subnet_id: "{{ item }}"
      assign_public_ip: yes
    register: ec2
    with_items:
      - vpc_subnet_id_a
      - vpc_subnet_id_b

  - name: Create Route 53 DNS entry
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "gluster-node-{{ item.1.id.split('-').1 }}.{{ r53_zone }}"
      ttl: 60
      type: A
      value: "{{ item.0.public_ip }}"
      overwrite: yes
    when: item.0.state == 'running'
    with_subelements:
      - ec2.results
      - instances

  - name: Wait for ssh
    wait_for:
      port: 22
      host: "{{ item.1.dns_name }}"
    when: item.1.state == "running"
    with_subelements:
    - ec2.results
    - instances