# vim: set ft=ansible:
---
- name: Configure the nodes
  hosts: localhost
  gather_facts: no
  connection: local
  become: False
  vars_files:
    - vars.yaml
  tasks:

  - name: debug sides variable
    debug: var=sides

  - name: Create ec2 instance
    ec2:
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      key_name: "{{ ec2_keypair }}"
      instance_type: "{{ ec2_instance_type }}"
      group_id: "{{ sg_group_id }}"
      instance_tags:
        Name: "{{ cluster_id }}"
        gluster_side: "{{ item.side_tag }}"
      exact_count: "{{ nodes_per_az }}"
      count_tag:
        Name: "{{ cluster_id }}"
        gluster-side: "{{ item.side_tag }}"
      wait: yes
      volumes:
        - volume_size: 10
          device_type: gp2
          device_name: /dev/sda1
          delete_on_termination: True
        - device_name: /dev/xvdb
          device_type: gp2
          volume_size: 10
          delete_on_termination: True
      assign_public_ip: yes
      vpc_subnet_id: "{{ item.subnet }}"
    with_items: sides
    register: ec2

  - name: Debug ec2 data structure
    debug: var=ec2
    when: debug_print == true

#  - name: Wait to be sure the instances are running
#    pause: seconds=30

  - name: Create Route 53 DNS entry
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "gluster-node-{{ item.id.split('-').1 }}.gluster.{{ r53_zone }}"
      ttl: 60
      type: A
      value: "{{ item.public_ip }}"
      overwrite: yes
    when: item.state == "running"
    with_items:
      - "{{ ec2.results.0.instances }}"
      - "{{ ec2.results.1.instances }}"

