# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  name: Prep for Gluster setup
  become: False
  vars_files:
    - vars.yaml
  vars:
    diff_hosts: ""
    gluster_server_list: []
    node_zero: ""
  tasks:

  - name: Build host list data structure
    set_fact:
      gluster_server_list: "{{ gluster_server_list + [ item.0 ] + [ item.1 ] }}"
    with_together:
      - "{{ groups.tag_gluster_side_side_a }}"
      - "{{ groups.tag_gluster_side_side_b }}"

  - name: Create gluster_hosts file locally
    template: src=glusterhosts.j2 dest=./gluster_hosts

  - name: Diff the gluster_hosts files
    shell: ./gluster_diff.py > diff_hosts

  - name: Set the node_zero variable
    set_fact:
      node_zero: "{{ lookup('file', './node_zero') }}"

  - name: Load the diff_hosts variable
    set_fact:
      diff_hosts: "{{ lookup('file', './diff_hosts') }}"

  - name: Debug the diff_hosts variable
    debug: var=diff_hosts

  - name: Create gluster_peer.sh script
    connection: local
    template: src=glusterpeersh.j2 dest=./gluster_peer.sh

  - name: Create add_brick.sh script
    connection: local
    template: src=glusteraddbrick.j2 dest=./gluster_addbrick.sh


- hosts: ec2
  name: Gluster setup
  become: True
  become_method: sudo
  vars_files:
    - vars.yaml
  vars:
    diff_hosts: ""
    gluster_server_list: []
    node_zero: ""
  tasks:

  - name: Build host list data structure
    set_fact:
      gluster_server_list: "{{ gluster_server_list + [ item.0 ] + [ item.1 ] }}"
    with_together:
      - "{{ groups.tag_gluster_side_side_a }}"
      - "{{ groups.tag_gluster_side_side_b }}"

  - name: Set the node_zero variable
    set_fact:
      node_zero: "{{ lookup('file', './node_zero') }}"

  - name: Load the diff_hosts variable
    set_fact:
      diff_hosts: "{{ lookup('file', './diff_hosts') }}"

  - name: Copy gluster_peer.sh script to nodes
    copy:
      src: ./gluster_peer.sh
      dest: /tmp/gluster_peer.sh
      owner: root
      mode: 0700

  - name: Copy add_brick.sh script to nodes
    copy:
      src: ./gluster_addbrick.sh
      dest: /tmp/gluster_addbrick.sh
      owner: root
      mode: 0700

  - name: Execute gluster_peer.sh script on nodes
    shell: /tmp/gluster_peer.sh
    ignore_errors: yes
    run_once: true
    delegate_to: "{{ node_zero }}"

  - name: Execute add_brick.sh script on nodes
    shell: /tmp/gluster_addbrick.sh
    run_once: true
    delegate_to: "{{ node_zero }}"
