# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  become: False
  gather_facts: no
  # Pull in access and secret keys, be sure to run ansible-playbook with
  # --ask-vault-pass, see README.md for more information
  vars_files:
    - vars.yaml

- include: create_vpc.yaml

# Set up security groups for the VPC
- include: create_security_groups.yaml
  vars:
    vpc_id: "{{ vpc.vpc_id }}"

# Create Route 53 entries
- include: create_route53.yaml

# Create Gluster nodes
- include: create_nodes_sidea.yaml
  vars:
    side_tag: gluster_sidea
    vpc_id: "{{ vpc.vpc_id }}"
    vpc_subnet_id: "{{ vpc.subnets.0.id }}"
    sg_group_id: "{{ group.group_id }}"
- include: create_nodes_sideb.yaml
  vars:
    side_tag: gluster_sideb
    vpc_id: "{{ vpc.vpc_id }}"
    vpc_subnet_id: "{{ vpc.subnets.1.id }}"
    sg_group_id: "{{ group.group_id }}"

# Update the security rules
- include: update_security_group.yaml
  vars:
    vpc_id: "{{ vpc.vpc_id }}"

# Install and configure Gluster
#- include: install_gluster.yaml