# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  become: False
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:

  - name: Load the group_id
    set_fact:
      group_id: "{{ lookup('file', './group_id_var') }}"

# Re-run this so we can grab the subnet IDs
- include: create_vpc.yaml

# Create Gluster nodes
- include: create_nodes.yaml
  vars:
    sides:
      - subnet: "{{ vpc.subnets.0.id }}"
        side_tag: "side_a"
      - subnet: "{{ vpc.subnets.1.id }}"
        side_tag: "side_b"
    sg_group_id: "{{ group_id }}"

# Update the security rules
- include: update_security_group.yaml
  vars:
    vpc_id: "{{ vpc.vpc_id }}"

# Configure the nodes
- include: configure_nodes.yaml

# Install and configure Gluster
- include: install_gluster.yaml
