# vim: set ft=ansible:
---
- hosts: ec2
  name: Gluster installation
  become: True
  become_method: sudo
  vars_files:
    - vars.yaml
  vars:
    - gluster_volume: demovol
    - gluster_replicas: 2
    - gluster_brick_dirs:
      - /bricks/brick1/brick
  tasks:

#    - name: Load bricks var
#      include_vars: ./bricks.yaml

    - name: Install EPEL repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Fetch glusterfs repo file
      get_url: dest=/etc/yum.repos.d/glusterfs-epel.repo
               url=http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo/glusterfs-epel.repo

    - name: Set repo file permissions
      file: owner=root group=root mode=0644
            path=/etc/yum.repos.d/glusterfs-epel.repo

    - name: Install glusterfs server packages (CentOS)
      yum: name={{ item }} state=installed enablerepo="glusterfs-epel"
      with_items:
        - glusterfs-server
        - glusterfs-client
        - attr

    - name: Ensure the GlusterFS service is running (CentOS)
      service: name=glusterd state=started

    - name: Create Gluster volume
      gluster_volume:
        bricks: "{{ gluster_brick_dirs | join(',') }}"
        cluster: "{{ groups.ec2 | join(',') }}"
        replicas: 2
        name: "{{ gluster_volume }}"
        host: "{{ inventory_hostname }}"
        state: present
      run_once: true

#    - name: Start Gluster volume
#      gluster_volume: name={{ gluster_volume }} state=started